<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-G1RVVOU2" failures="1" tests="4" name="Test2" time="0.075" errors="0" timestamp="2023-04-03T23:32:51 IST">
  <testcase classname="TestCases.TestCase2" name="validateTitle" time="0.006">
    <failure type="java.lang.AssertionError" message="failing test case">
      <![CDATA[java.lang.AssertionError: failing test case
at TestCases.TestCase2.validateTitle(TestCase2.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- validateTitle -->
  <testcase classname="TestCases.TestCase2" name="validateHeading" time="0.0">
    <skipped/>
  </testcase> <!-- validateHeading -->
  <testcase classname="TestCases.TestCase2" name="testLogin" time="0.006"/>
  <testcase classname="TestCases.TestCase2" name="skipTest" time="0.002">
    <skipped/>
  </testcase> <!-- skipTest -->
</testsuite> <!-- Test2 -->
